### ISSUE TITLE
how to handle existing doc being selected as winner among forks?

### ISSUE THREAD

**Issue by sethvincent** [digidem/mapeo-sqlite-indexer#5]
Right now in mapeo-core-next we're relying on the `onceWriteDoc` as a one-time use event listener.

This fires only when a new doc is written to the database via `dbApi.writeDoc`: https://github.com/digidem/mapeo-sqlite-indexer/blob/main/index.js#L92

But in the (somewhat rare) case where a new doc is not selected as a winner, `onceWriteDoc` will never fire and the async method in mapeo-core-next will stall. @gmaclennan it turns out this was the error I was seeing that I mentioned in our meeting today.

Maybe `onceWriteDoc` should be something more generic? Either with a different name, or it's just also called after updateForks at this particular if statement?: https://github.com/digidem/mapeo-sqlite-indexer/blob/main/index.js#L216

I'm not completely sure if there's other if/else branches in `_batch` that would also need to be handled.

It would be useful feedback in that `onceWriteDoc` listener to know if the existing doc was chosen as winner.

**Comment by gmaclennan** [comment]
Ah yes good point.

So maybe the name should be `onceIndexedDoc` (e.g. fired once the doc has been indexed), and it should return:

1. The actual doc that was indexed (e.g. the one that was originally written to the hypercore that we want to track through the indexing pipeline)
2. It should indicate if it was not the "winner"
3. Should probably also return the "winner", so the frontend could decide to display that instead.
4.

**Comment by gmaclennan** [comment]
This is now handled in @mapeo/core. The DataStore waits for the [doc that is written to be indexed, and returns that doc](https://github.com/digidem/mapeo-core-next/blob/7ec98afe3d28e85caf33aabeb1333916ac8fe564/src/datastore/index.js#L152-L157) (whether it was the winner or not). The DataType [returns the winner](https://github.com/digidem/mapeo-core-next/blob/7ec98afe3d28e85caf33aabeb1333916ac8fe564/src/datatype/index.js#L171-L172), after the updated doc has been indexed.
